# -*- coding: utf-8 -*-
"""Assignment 4 on class 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dh_xzm-_QVE2CYqiqgaQvItUl8inBGf4
"""

import math


def dis(x1,y1,x2,y2):
  return math.sqrt((x1-x2)**2 + (y1-y2)**2)

x_A=[10]
y_A=[0]
x_B=[0]
y_B=[10]
x_C=[10]
y_C=[10]
x_D=[0]
y_D=[0]

v_A=3
v_B=5
v_C=7
v_D=2


#hit
h_A=0
h_B=0
h_C=0
h_D=0

distDB= dis(x_D[0],y_D[0],x_B[0],y_B[0])
distCA= dis(x_C[0],y_C[0],x_A[0],y_A[0])
distBC= dis(x_B[0],y_B[0],x_C[0],y_C[0])
distAD= dis(x_A[0],y_A[0],x_D[0],y_D[0])

for t in range(1,20):
  print("At time =",t)
  #D is chased by B target-D 
  sin = (y_D[t-1]- y_B[t-1]) / distDB
  cos= (x_D[t-1] - x_B[t-1]) / distDB
  new_x_B= x_B[t-1]+ v_B* cos
  new_y_B= y_B[t-1] + v_B*sin
  x_B.append(new_x_B)
  y_B.append(new_y_B)

  #C is chased by A Target- C 
  sin = (y_C[t-1]- y_A[t-1]) / distCA
  cos= (x_C[t-1] - x_A[t-1]) / distCA
  new_x_A= x_A[t-1]+ v_A* cos
  new_y_A= y_A[t-1] + v_A*sin
  x_A.append(new_x_A)
  y_A.append(new_y_A)

  #B is chased by C
  sin = (y_B[t-1]- y_C[t-1]) / distBC
  cos= (x_B[t-1] - x_C[t-1]) / distBC
  new_x_C= x_C[t-1]+ v_C* cos
  new_y_C= y_C[t-1] + v_C*sin
  x_C.append(new_x_C)
  y_C.append(new_y_C)

  #A is chased by D
  sin = (y_A[t-1]- y_D[t-1]) / distAD
  cos= (x_A[t-1] - x_D[t-1]) / distAD
  new_x_D= x_D[t-1]+ v_D* cos
  new_y_D= y_D[t-1] + v_D*sin
  x_D.append(new_x_D)
  y_D.append(new_y_D)

  #x_D.append(x_D[t-1]+v_D)  #d fixed kore deya
  #y_D.append(y_D[t-1])

  distDB=math.sqrt((x_D[t]-x_B[t])**2 + (y_D[t]-y_B[t])**2)
  distCA=math.sqrt((x_C[t]-x_A[t])**2 + (y_C[t]-y_A[t])**2)
  distBC=math.sqrt((x_B[t]-x_C[t])**2 + (y_B[t]-y_C[t])**2)
  distAD=math.sqrt((x_A[t]-x_D[t])**2 + (y_A[t]-y_D[t])**2)

  if distDB<5:
    print(" B shoot D, Distance DB=",distDB)
    h_B=h_B+1

  if distCA<5:
    print(" A shoot C, Distance CA=",distCA)
    h_A=h_A+1

  if distBC<5:
    print(" C shoot B, Distance BC=",distBC)
    h_C=h_C+1

  if distAD<5:
    print(" D shoot A, Distance AD",distAD)
    h_D=h_D+1


print("Car A was shot ", h_D, " times")
print("Car B was shot ", h_C, " times")
print("Car C was shot ", h_A, " times")
print("Car D was shot ", h_B, " times")

import matplotlib.pyplot as plt 
# Car A
x_A
y_A

plt.plot(x_A, y_A, color= 'red',label = "car A") 
  
# Car B
x_B
y_B

plt.plot(x_B, y_B, color= 'blue',label = "car B") 

# Car C
x_C
y_C

plt.plot(x_C, y_C, color= 'green',label = "car C") 

# Car D
x_D
y_D

plt.plot(x_D, y_D, color= 'orange',label = "car D") 
      
  
 

# function to show the plot 
plt.show()